import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { FaTwitter, FaLinkedin, FaGithub } from "react-icons/fa";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <div className={styles.btnContainer}>
        <a href="ashliecv.pdf" target="_blank">
          <button className={styles.resumeBtn}>Resume</button>
        </a>
      </div>
      <footer className={styles.footer}>
        <button>
          <a
            href="https://twitter.com/ashliecodes"
            target="_blank"
            rel="noreferrer"
          >
            <FaTwitter size="40px" />
          </a>
        </button>

        <button>
          <a
            href="https://www.linkedin.com/in/ashlie-p-a0131317a/"
            target="_blank"
            rel="noreferrer"
          >
            <FaLinkedin size="40px" />
          </a>
        </button>
        <button>
          <a
            href="https://github.com/ashliecodes"
            target="_blank"
            rel="noreferrer"
          >
            <FaGithub size="40px" />
          </a>
        </button>
      </footer>
    </div>
  );
}
